name: Deploy Go API Lambda Function

#on:
#  workflow_run:
#    workflows: ["Terraform"]
#    types:
#      - completed

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build Lambda Function
        working-directory: api
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          GOOS=linux go build -o api-lambda-function main.go
          zip api-lambda-function.zip api-lambda-function

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Lambda function
        working-directory: api
        run: |
          aws lambda update-function-code --function-name ct_ak_hello_world_api --zip-file fileb://api-lambda-function.zip




