name: 'Terraform Workflow'

on:
  push:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      # Allow to run job and deploy to diff environments
      # by substituting different variables and triggering off of branch names
      # or actions like merging a PR
      - name: Terraform DEV Environment
        if: github.ref == 'refs/heads/develop'
        uses: ./.github/actions/terraform-job
        with:
          working_directory: 'terraform/workspaces/dev/api'

