name: 'Terraform Workflow'

on: [push]

permissions:
  contents: read

jobs:
  terraform-development:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: Development

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      # Allow to run job and deploy to diff environments
      # by substituting different variables and triggering off of branch names
      # or actions like merging a PR
      - name: Terraform DEV Environment
        if: startsWith(github.ref, 'refs/heads/feature/')
        uses: ./.github/actions/terraform-job
        with:
          working_directory: 'terraform/workspaces/dev/api'

